<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="CopyWebRtcVadFiles" AfterTargets="AfterBuild">
		<PropertyGroup>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$(PlatformTarget)' == 'x86'">win-x86</WebRtcRid>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$(PlatformTarget)' == 'x64'">win-x64</WebRtcRid>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$(PlatformTarget)' == 'ARM64'">win-arm64</WebRtcRid>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$(WebRtcRid)' == ''">win-x64</WebRtcRid>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('Linux')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">linux-x64</WebRtcRid>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('Linux')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">linux-arm64</WebRtcRid>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('OSX')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">osx-arm64</WebRtcRid>
			<WebRtcRid Condition="$([MSBuild]::IsOSPlatform('OSX')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">osx-x64</WebRtcRid>
		</PropertyGroup>
		<ItemGroup>
			<WebRtcVadFiles Include="$(MSBuildThisFileDirectory)runtimes\$(WebRtcRid)\native\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(WebRtcVadFiles)" DestinationFolder="$(OutputPath)" Condition="'@(WebRtcVadFiles)' != ''" />
	</Target>
</Project>
